### ISSUE TITLE
Ponto de melhoria

### ISSUE THREAD

**Issue by jordyalcides** [guilhermeluciojardim/CoronaKiller#2]
Infelizmente o seu link de demo tá retornando um erro! 😞 

<img width="463" alt="Screen Shot 2022-08-05 at 08 50 18" src="https://user-images.githubusercontent.com/9451041/183071737-057e38e3-41ed-4a27-a360-d73b31240194.png">

**Comment by guilhermeluciojardim** [comment]
Esse erro esta dando hoje com todos os jogos do unity play.. creio ser um problema do servidor do unity e nao do jogo em si. aguardamos um tempo e vemos se normaliza
